[package]
name = "hack_assembly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
dict = "0.1.5"
progress_bar = "1.0.3"
regex = "1.7.1"
